"""
    Dev

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import canonical
from canonical.model.user_in_create import UserInCreate


class TestUserInCreate(unittest.TestCase):
    """UserInCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInCreate(self):
        """Test UserInCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserInCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
