"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.game_in_create import GameInCreate
globals()['GameInCreate'] = GameInCreate
from cannonical.model.body_games_create_game_api_games_post import BodyGamesCreateGameApiGamesPost


class TestBodyGamesCreateGameApiGamesPost(unittest.TestCase):
    """BodyGamesCreateGameApiGamesPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyGamesCreateGameApiGamesPost(self):
        """Test BodyGamesCreateGameApiGamesPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyGamesCreateGameApiGamesPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
