"""
    Dev

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import canonical
from canonical.model.game_in_update import GameInUpdate
globals()['GameInUpdate'] = GameInUpdate
from canonical.model.body_games_update_game_api_games_id_patch import BodyGamesUpdateGameApiGamesIdPatch


class TestBodyGamesUpdateGameApiGamesIdPatch(unittest.TestCase):
    """BodyGamesUpdateGameApiGamesIdPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyGamesUpdateGameApiGamesIdPatch(self):
        """Test BodyGamesUpdateGameApiGamesIdPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyGamesUpdateGameApiGamesIdPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
