"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.user import User
globals()['User'] = User
from cannonical.model.user_in_response import UserInResponse


class TestUserInResponse(unittest.TestCase):
    """UserInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInResponse(self):
        """Test UserInResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserInResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
