"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.user_in_create import UserInCreate
globals()['UserInCreate'] = UserInCreate
from cannonical.model.body_users_create_user_api_users_post import BodyUsersCreateUserApiUsersPost


class TestBodyUsersCreateUserApiUsersPost(unittest.TestCase):
    """BodyUsersCreateUserApiUsersPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyUsersCreateUserApiUsersPost(self):
        """Test BodyUsersCreateUserApiUsersPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyUsersCreateUserApiUsersPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
