"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.user_in_update import UserInUpdate
globals()['UserInUpdate'] = UserInUpdate
from cannonical.model.body_users_update_user_api_users_id_patch import BodyUsersUpdateUserApiUsersIdPatch


class TestBodyUsersUpdateUserApiUsersIdPatch(unittest.TestCase):
    """BodyUsersUpdateUserApiUsersIdPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyUsersUpdateUserApiUsersIdPatch(self):
        """Test BodyUsersUpdateUserApiUsersIdPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyUsersUpdateUserApiUsersIdPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
