"""
    Dev

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import canonical
from canonical.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_create_user_api_users_post(self):
        """Test case for users_create_user_api_users_post

        Users:Create-User  # noqa: E501
        """
        pass

    def test_users_delete_user_api_users_id_delete(self):
        """Test case for users_delete_user_api_users_id_delete

        Users:Delete-User  # noqa: E501
        """
        pass

    def test_users_get_user_api_users_id_get(self):
        """Test case for users_get_user_api_users_id_get

        Users:Get-User  # noqa: E501
        """
        pass

    def test_users_list_users_api_users_get(self):
        """Test case for users_list_users_api_users_get

        Users:List-Users  # noqa: E501
        """
        pass

    def test_users_update_user_api_users_id_patch(self):
        """Test case for users_update_user_api_users_id_patch

        Users:Update-User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
