"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.user import User
globals()['User'] = User
from cannonical.model.list_of_users_in_response import ListOfUsersInResponse


class TestListOfUsersInResponse(unittest.TestCase):
    """ListOfUsersInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListOfUsersInResponse(self):
        """Test ListOfUsersInResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListOfUsersInResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
