"""
    Dev

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import canonical
from canonical.model.game import Game


class TestGame(unittest.TestCase):
    """Game unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGame(self):
        """Test Game"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Game()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
