"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cannonical
from cannonical.model.game_in_create import GameInCreate


class TestGameInCreate(unittest.TestCase):
    """GameInCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameInCreate(self):
        """Test GameInCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GameInCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
