"""
    Dev

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import canonical
from canonical.model.game_in_update import GameInUpdate


class TestGameInUpdate(unittest.TestCase):
    """GameInUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameInUpdate(self):
        """Test GameInUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GameInUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
