# flake8: noqa

"""
    Canonical Take Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from cannonical.api_client import ApiClient

# import Configuration
from cannonical.configuration import Configuration

# import exceptions
from cannonical.exceptions import OpenApiException
from cannonical.exceptions import ApiAttributeError
from cannonical.exceptions import ApiTypeError
from cannonical.exceptions import ApiValueError
from cannonical.exceptions import ApiKeyError
from cannonical.exceptions import ApiException
